services:
  - type: web
    name: chromaclairvoyant
    env: python
    buildCommand: "sh build.sh"
    startCommand: "gunicorn web_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,chromaclairvoyant.onrender.com
